Bugfix/sidebar
ScottHarrisonDev/playlist-curator pull request #4
Opened 2018-10-03 23:40 UTC by klauskpm

The sidebar starts closed, and slides when there is a selected track.

This closes issue #2

2018-10-04 23:37 UTC, klauskpm commented
Hey @ScottHarrisonDev . The conflicts are now resolved!

2018-10-05 12:25 UTC, ScottHarrisonDev requested changes

2018-10-05 12:25 UTC, ScottHarrisonDev commented on index.html
> +            oie
I assume this is a typo? Works great other than this issue, if this is removed I'll accept the PR 👍

2018-10-05 13:32 UTC, klauskpm commented on index.html
> +            oie
Yes, it is. Sorry about that. I'm changing it right away 👍

2018-10-05 14:08 UTC, ScottHarrisonDev approved these changes

2018-10-05 14:08 UTC, merged

2018-10-05 14:08 UTC, ScottHarrisonDev commented
Great!

2018-10-05 17:30 UTC, klauskpm commented
Thank you :)